---
- name: Render kube-proxy systemd service file
  template: src=kube-proxy.service.j2 dest=/etc/systemd/system/kube-proxy.service

- name: Enable kube-proxy service
  shell: systemctl enable kube-proxy
  ignore_errors: true

- name: Start kube-proxy service
  shell: systemctl daemon-reload && systemctl restart kube-proxy