---
- name: Copy helm binary
  copy: src={{ item }} dest=/root/local/bin/{{ item }} mode=0755 owner=root
  with_items:
    - helm
  tags:
    - helm

- name: Set Helm Stable repo
  shell: |
    /root/local/bin/helm repo add stable https://charts.helm.sh/stable
    /root/local/bin/helm repo add kubernetes-dashboard https://kubernetes.github.io/dashboard/
  tags:
    - helm-stable-repo