---
- name: Copy helm binary
  copy: src={{ item }} dest=/root/local/bin/{{ item }} mode=0755 owner=root
  with_items:
    - helm
  tags:
    - helm

- name: Set Helm Stable repo
  shell: |
    /root/local/bin/helm repo add stable https://fumanne.github.io/helm-chart-mirror
  tags:
    - helm-stable-repo