---
- name: Create Binary directory
  file: path={{ item }} state=directory owner=root group=root mode=0755
  with_items:
    - /root/local/bin
    - /etc/kubernetes/ssl
    - /etc/docker
    - /root/.kube/
    - /opt/cni/bin
    - /etc/cni/net.d

- name: Upgrade all packages
  yum: name=* state=latest

- name: Setting timezone to UTC
  timezone:
    name: UTC

- name: Restart cron (apply UTC)
  service:
    name: crond
    state: restarted
  changed_when: False

- name: Install base package
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - bind-utils
    - wget
    - NetworkManager
    - dstat
    - bash-completion
    - telnet
    - gcc
    - make
    - libnftnl-devel
    - libmnl-devel
    - autoconf
    - automake
    - libtool
    - bison
    - flex
    - libnetfilter_conntrack-devel
    - libnetfilter_queue-devel
    - libpcap-devel
    - bzip2
    - socat
    - psmisc
    - nfs-utils
    - net-tools
    - ipset
    - ipvsadm
    - conntrack
  ignore_errors: yes

- name: Delete Centos Default Packages
  yum:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - firewalld
    - python-firewall
    - firewalld-filesystem

- name: Copy Variable Package
  copy: src={{ item }} dest=/root/local/bin/{{ item }} mode=0755
  with_items:
    - cfssl
    - cfssl-certinfo
    - cfssljson
    - kubectl

- name: Copy SSH Private Key
  copy:
    src: "{{ item }}"
    dest: /root/
    mode: 0600
  with_fileglob:
    - "{{ role_path }}/../bootstrap/files/*.pem"
