---

- name: Create kubelet Dir
  file: path={{ item }} state=directory owner=root group=root mode=0755
  with_items:
    - /var/lib/kubelet
    - /etc/cni/net.d

- name: Copy kubelet binary
  copy: src={{ item }} dest=/root/local/bin/{{ item }} mode=0755
  with_items:
  - kubelet

- name: Put cni plguin in /opt/cni/bin
  copy: src={{ item }} dest=/opt/cni/bin/{{ item }} mode=0755
  with_items:
  - bridge
  - loopback
  - host-local
  - flannel
  - firewall
  - portmap
  - static
  - vlan
  - tuning
  - macvlan


- name: Render cni config file
  template: src=cni-default.conf.j2 dest=/etc/cni/net.d/10-default.conf

- name: Render cloud-config file
  template: src=aws-cloud-config.j2 dest=/etc/kubernetes/cloud-config

