---
- name: Render kubelet systemd service file
  template: src=kubelet.service.j2 dest=/etc/systemd/system/kubelet.service

- name: Enable kubelet  service
  shell: systemctl enable kubelet
  ignore_errors: true

- name: Start kubelet service
  shell: systemctl daemon-reload && systemctl restart kubelet

- name: Check kubeket running
  shell: "systemctl status kubelet.service|grep Active"
  register: kubelet_status
  until: '"running" in kubelet_status.stdout'
  retries: 8
  delay: 2