---
- name: Render admin CA CSR
  template: src=admin-csr.json.j2 dest=/etc/kubernetes/ssl/admin-csr.json

- name: Create admin CA
  shell: "cd /etc/kubernetes/ssl && /root/local/bin/cfssl gencert \
        -ca=/etc/kubernetes/ssl/ca.pem \
        -ca-key=/etc/kubernetes/ssl/ca-key.pem \
        -config=/etc/kubernetes/ssl/ca-config.json \
        -profile=kubernetes admin-csr.json | /root/local/bin/cfssljson -bare admin"

- name: Set cluster name by kubernetes
  shell: "/root/local/bin/kubectl config set-cluster kubernetes \
        --certificate-authority=/etc/kubernetes/ssl/ca.pem \
        --embed-certs=true \
        --server={{ KUBE_APISERVER }}"

- name: Set credentials for cluster by admin auth
  shell: "/root/local/bin/kubectl config set-credentials admin \
        --client-certificate=/etc/kubernetes/ssl/admin.pem \
        --embed-certs=true \
        --client-key=/etc/kubernetes/ssl/admin-key.pem"

- name: Set context for cluster by admin
  shell: "/root/local/bin/kubectl config set-context kubernetes \
        --cluster=kubernetes --user=admin"

- name: Use  context by kubernete
  shell: "/root/local/bin/kubectl config use-context kubernetes"


