---
- name: 准备kubectl使用的admin 证书签名请求
  template: src=admin-csr.json.j2 dest=/etc/kubernetes/ssl/admin-csr.json

- name: 创建 admin证书与私钥
  shell: "cd /etc/kubernetes/ssl && /root/local/bin/cfssl gencert \
        -ca=/etc/kubernetes/ssl/ca.pem \
        -ca-key=/etc/kubernetes/ssl/ca-key.pem \
        -config=/etc/kubernetes/ssl/ca-config.json \
        -profile=kubernetes admin-csr.json | /root/local/bin/cfssljson -bare admin"

- name: 设置集群参数
  shell: "/root/local/bin/kubectl config set-cluster kubernetes \
        --certificate-authority=/etc/kubernetes/ssl/ca.pem \
        --embed-certs=true \
        --server={{ KUBE_APISERVER }}"

- name: 设置客户端认证参数
  shell: "/root/local/bin/kubectl config set-credentials admin \
        --client-certificate=/etc/kubernetes/ssl/admin.pem \
        --embed-certs=true \
        --client-key=/etc/kubernetes/ssl/admin-key.pem"

- name: 设置上下文参数
  shell: "/root/local/bin/kubectl config set-context kubernetes \
        --cluster=kubernetes --user=admin"

- name: 选择默认上下文
  shell: "/root/local/bin/kubectl config use-context kubernetes"


