---
- name: Render aggreator proxy CA CSR
  template: src=aggregator-proxy-csr.json.j2 dest=/etc/kubernetes/ssl/aggregator-proxy-csr.json

- name: Create aggregator proxy CA
  shell: "cd /etc/kubernetes/ssl && /root/local/bin/cfssl gencert \
        -ca=/etc/kubernetes/ssl/ca.pem \
        -ca-key=/etc/kubernetes/ssl/ca-key.pem \
        -config=/etc/kubernetes/ssl/ca-config.json \
        -profile=kubernetes aggregator-proxy-csr.json | /root/local/bin/cfssljson -bare aggregator-proxy"


