---

- name: Render CA Json
  template: src=ca-config.json.j2 dest=/etc/kubernetes/ssl/ca-config.json

- name: Render CA CSR
  template: src=ca-csr.json.j2 dest=/etc/kubernetes/ssl/ca-csr.json

- name: Create root CA
  shell: "cd /etc/kubernetes/ssl && /root/local/bin/cfssl gencert -initca ca-csr.json | /root/local/bin/cfssljson -bare ca"
