---

- name: Render etcd CSR
  template: src=etcd-csr.json.j2 dest=/etc/kubernetes/ssl/etcd-csr.json

- name: Create etcd CA
  shell: "cd /etc/kubernetes/ssl && /root/local/bin/cfssl gencert \
        -ca=/etc/kubernetes/ssl/ca.pem \
        -ca-key=/etc/kubernetes/ssl/ca-key.pem \
        -config=/etc/kubernetes/ssl/ca-config.json \
        -profile=kubernetes etcd-csr.json | /root/local/bin/cfssljson -bare etcd"

