---

- name: 准备kube-proxy 证书签名请求
  template: src=kube-proxy-csr.json.j2 dest=/etc/kubernetes/ssl/kube-proxy-csr.json

- name: 创建 kube-proxy证书与私钥
  shell: "cd /etc/kubernetes/ssl && /root/local/bin/cfssl gencert \
        -ca=/etc/kubernetes/ssl/ca.pem \
        -ca-key=/etc/kubernetes/ssl/ca-key.pem \
        -config=/etc/kubernetes/ssl/ca-config.json \
        -profile=kubernetes kube-proxy-csr.json | /root/local/bin/cfssljson -bare kube-proxy"

- name: 设置集群参数
  shell: "/root/local/bin/kubectl config set-cluster kubernetes \
        --certificate-authority=/etc/kubernetes/ssl/ca.pem \
        --embed-certs=true \
        --server={{ KUBE_APISERVER }} \
        --kubeconfig=/etc/kubernetes/kube-proxy.kubeconfig"
- name: 设置客户端认证参数
  shell: "/root/local/bin/kubectl config set-credentials kube-proxy \
        --client-certificate=/etc/kubernetes/ssl/kube-proxy.pem \
        --client-key=/etc/kubernetes/ssl/kube-proxy-key.pem \
        --embed-certs=true \
        --kubeconfig=/etc/kubernetes/kube-proxy.kubeconfig"
- name: 设置上下文参数
  shell: "/root/local/bin/kubectl config set-context default \
        --cluster=kubernetes \
        --user=kube-proxy \
        --kubeconfig=/etc/kubernetes/kube-proxy.kubeconfig"
- name: 选择默认上下文
  shell: "/root/local/bin/kubectl config use-context default --kubeconfig=/etc/kubernetes/kube-proxy.kubeconfig"



