---

- name: Disable selinux temporary
  shell: "setenforce 0"
  failed_when: false

- name: Disable selinux forever
  lineinfile:
    dest: /etc/selinux/config
    regexp: "^SELINUX="
    line: "SELINUX=disabled"

