---

- name: Copy etcd binary file
  copy: src={{ item }} dest=/root/local/bin/{{ item }} mode=0755
  with_items:
  - etcd
  - etcdctl

- name: Create etcd Dir
  file: name=/var/lib/etcd state=directory owner=root group=root mode=0755