---
- name: Render etcd systemd service file
  template: src=etcd.service.j2 dest=/etc/systemd/system/etcd.service

- name: Enable etcd service
  shell: systemctl enable etcd
  ignore_errors: true

- name: Start etcd service
  shell: systemctl daemon-reload && systemctl restart etcd