---

- name: Install metrics-server with Helm
  shell: |
    /root/local/bin/helm upgrade -i metrics-server --namespace kube-system --set args={"--kubelet-insecure-tls"},hostNetwork.enabled=true --debug --wait --force stable/metrics-server
