---
# 如果service 要用LoadBalancer 类型, 需要在aws vpc中将公有子网 打上 KubernetesClusterTag 的tag, Value 随意

- name: Install Promtheus with Helm
  shell: |
    /root/local/bin/helm upgrade -i prometheus --namespace kube-system --set server.service.type=LoadBalancer,server.retention="7d",server.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-type"=nlb --debug --wait --force stable/prometheus
