---

- name: 创建kube-apiserver的systemd unit文件
  template: src=kube-apiserver.service.j2 dest=/etc/systemd/system/kube-apiserver.service

- name: enable master 服务
  shell: systemctl enable kube-apiserver
  ignore_errors: true

- name: 启动 master 服务
  shell: "systemctl daemon-reload && systemctl restart kube-apiserver"

- name: 以轮询的方式等待master服务启动完成
  uri:
    url: "{{ KUBE_APISERVER }}"
    method: GET
    status_code: 401
    validate_certs: no
  register: _result
  until: _result.status == 401
  retries: 30 # retry X times
  delay: 10 # pause for X sexc b/w each call