---

- name: Render kube-apiserver systemd service file
  template: src=kube-apiserver.service.j2 dest=/etc/systemd/system/kube-apiserver.service

- name: Enable kube-apiserver service
  shell: systemctl enable kube-apiserver
  ignore_errors: true

- name: Start kube-apiserver service
  shell: "systemctl daemon-reload && systemctl restart kube-apiserver"

- name: Check kube-apiserver running
  uri:
    url: "{{ KUBE_APISERVER }}"
    method: GET
    status_code: 401
    validate_certs: no
  register: _result
  until: _result.status == 401
  retries: 30 # retry X times
  delay: 10 # pause for X sexc b/w each call