---
- name: Create flannel cni Dir
  file: path=/root/local/flannel/ state=directory owner=root group=root mode=0755

- name: Prepare flannel DaemonSet yaml file
  template: src=kube-flannel.yaml.j2 dest=/root/local/flannel/kube-flannel.yaml