---

- name: Copy docker binary
  copy: src={{ item }} dest=/root/local/bin/{{ item }} mode=0755
  with_items:
  - containerd
  - containerd-shim
  - docker-init
  - runc
  - docker
  - ctr
  - dockerd
  - docker-proxy
  - docker-compose

