---

- name: Render docker systemd service file
  template: src=docker.service.j2 dest=/etc/systemd/system/docker.service

- name: Enable docker service
  shell: systemctl enable docker

- name: Start docker service
  shell: systemctl daemon-reload && systemctl restart docker