---

- name: Scp admin service account yaml File
  copy: src=admin-serviceaccount.yaml dest=/root/admin-serviceaccount.yaml mode=0755
  tags:
    - admin-sa

- name: Create admin service account
  shell: |
    /root/local/bin/kubectl apply -f /root/admin-serviceaccount.yaml
  tags:
    - admin-sa