---

- hosts: deploy,kube-master,node14
  roles:
    - base-package
    - os
    - docker

- hosts: deploy
  roles:
    - ca-init

- hosts: kube-master,node14
  roles:
    - ca-distribution

- hosts: kube-master
  roles:
    - etcd
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
    - kubelet
    - kube-proxy

- hosts: deploy
  roles:
    - bootstrap-kubeconfig


- hosts: node14
  roles:
    - kubelet
    - kube-proxy

- hosts: deploy
  roles:
    - { role: calico, when: "CLUSTER_NETWORK == 'calico'" }
    - { role: aws-vpc-cni, when: "CLUSTER_NETWORK == 'aws-vpc-cni'" }

- hosts:
  - kube-master
  - kube-node
  roles:
    - { role: flannel, when: "CLUSTER_NETWORK == 'flannel'" }

- hosts: all
  roles:
    - default-cni

- hosts: deploy
  roles:
    - helm
    - aws-ebs

