---

- name: 创建kube-scheduler的systemd unit文件
  template: src=kube-scheduler.service.j2 dest=/etc/systemd/system/kube-scheduler.service

- name: enable kube-scheduler 服务
  shell: systemctl enable kube-scheduler
  ignore_errors: true

- name: 启动 kube-scheduler 服务
  shell: "systemctl daemon-reload && systemctl restart kube-scheduler"