---

- name: Render kube-scheduler systemd service file
  template: src=kube-scheduler.service.j2 dest=/etc/systemd/system/kube-scheduler.service

- name: Enable kube-scheduler service
  shell: systemctl enable kube-scheduler
  ignore_errors: true

- name: Start kube-scheduler service
  shell: "systemctl daemon-reload && systemctl restart kube-scheduler"