---
- name: Distrube admin CA to all node
  copy: src={{ item }} dest={{ item }} mode=0755 owner=root
  with_items:
    - /etc/kubernetes/ssl/admin.pem
    - /etc/kubernetes/ssl/admin-key.pem
    - /etc/kubernetes/ssl/admin.csr

- name: Dirtrube kubectl kubeconfig to all node
  copy: src={{ item }} dest={{ item }} mode=0755 owner=root
  with_items:
    - /root/.kube/config