---
- name: 分发admin 证书 至所有节点
  copy: src={{ item }} dest={{ item }} mode=0755 owner=root
  with_items:
    - /etc/kubernetes/ssl/admin.pem
    - /etc/kubernetes/ssl/admin-key.pem
    - /etc/kubernetes/ssl/admin.csr

- name: 分发kubectl 所需的kubeconfig 至 所有节点
  copy: src={{ item }} dest={{ item }} mode=0755 owner=root
  with_items:
    - /root/.kube/config