---
- name: 分发 aggregator-proxy 证书 至所有master节点
  copy: src={{ item }} dest={{ item }} mode=0755 owner=root
  with_items:
    - /etc/kubernetes/ssl/aggregator-proxy.pem
    - /etc/kubernetes/ssl/aggregator-proxy-key.pem
    - /etc/kubernetes/ssl/aggregator-proxy.csr