---

- name: 分发 kubernetes 证书 至所有节点
  copy: src={{ item }} dest={{ item }} mode=0755 owner=root
  with_items:
    - /etc/kubernetes/ssl/kubernetes.pem
    - /etc/kubernetes/ssl/kubernetes-key.pem
    - /etc/kubernetes/ssl/kubernetes.csr