---

- name: Render kube-controller-manager systemd service file
  template: src=kube-controller-manager.service.j2 dest=/etc/systemd/system/kube-controller-manager.service

- name: Enable kube-controller-manager service
  shell: systemctl enable kube-controller-manager
  ignore_errors: true

- name: Start kube-controller-manager service
  shell: "systemctl daemon-reload && systemctl restart kube-controller-manager"