---

- name: 创建kube-controller-manager的systemd unit文件
  template: src=kube-controller-manager.service.j2 dest=/etc/systemd/system/kube-controller-manager.service

- name: enable kube-controller-manager 服务
  shell: systemctl enable kube-controller-manager
  ignore_errors: true

- name: 启动 kube-controller-manager 服务
  shell: "systemctl daemon-reload && systemctl restart kube-controller-manager"